from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from doc_textify.evaluation import evaluate_textification


def main() -> int:
    parser = argparse.ArgumentParser(description="Score a doc-textify JSON output against a hand-labeled ground truth.")
    parser.add_argument("--actual", required=True, type=Path, help="JSON sidecar generated by doc-textify.")
    parser.add_argument("--expected", required=True, type=Path, help="Hand-labeled expected JSON.")
    parser.add_argument("--out", type=Path, help="Optional Markdown report path.")
    parser.add_argument("--json-out", type=Path, help="Optional machine-readable score JSON path.")
    args = parser.parse_args()

    result, report = evaluate_textification(args.actual, args.expected)
    print(report)
    if args.out:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(report, encoding="utf-8")
    if args.json_out:
        args.json_out.parent.mkdir(parents=True, exist_ok=True)
        args.json_out.write_text(json.dumps(result, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
